version: '3'

services:
  db:
    image: mysql
    command: --character-set-server=utf8 && --collation-server=utf8_unicode_ci 
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django_database
      MYSQL_USER: django_user
      MYSQL_PASSWORD: django_password
  adminer:
    image: adminer
    ports:
      - 8080:8080
  web:
    build: .
    command: python3 manage.py runserver 8765 
    volumes:
      - .:/usr/src/app
    ports:
      - "8088:8765"
    depends_on:
      - db
